<?php
  $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
  $this->headTitle()->setSeparator(' - ');
  $this->headTitle('Zend Framework Tutorial');
  echo $this->doctype(); 
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>

    <title>Test Application</title>

    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>

  </head>
  <body>

    <div id="content">
      <?php echo $this->layout()->content; ?>
    </div>

  </body>
</html>
